!function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=0)}([function(e,t){var r,n;r={"./node_modules/itty-router/dist/itty-router.min.js":
/*!**********************************************************!*\
  !*** ./node_modules/itty-router/dist/itty-router.min.js ***!
  \**********************************************************/e=>{e.exports={Router:function({base:e="",routes:t=[]}={}){return{__proto__:new Proxy({},{get:(r,n,o)=>(r,...s)=>t.push([n.toUpperCase(),RegExp(`^${(e+r).replace(/(\/?)\*/g,"($1.*)?").replace(/\/$/,"").replace(/:(\w+)(\?)?(\.)?/g,"$2(?<$1>[^/]+)$2$3").replace(/\.(?=[\w(])/,"\\.").replace(/\)\.\?\(([^\[]+)\[\^/g,"?)\\.?($1(?<=\\.)[^\\.")}/*$`),s])&&o}),routes:t,async handle(e,...r){let n,o,s=new URL(e.url);for(var[u,a,i]of(e.query=Object.fromEntries(s.searchParams),t))if((u===e.method||"ALL"===u)&&(o=s.pathname.match(a)))for(var l of(e.params=o.groups,i))if(void 0!==(n=await l(e.proxy||e,...r)))return n}}}}},"./src/api/routes/authentication.ts":
/*!******************************************!*\
  !*** ./src/api/routes/authentication.ts ***!
  \******************************************/(e,t,r)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0});const n=r(/*! itty-router */"./node_modules/itty-router/dist/itty-router.min.js").Router({base:"/api/authentication"});n.all("/",()=>new Response(JSON.stringify({ping:"pong"}))),t.default=n},"./src/api/routes/credentials.ts":
/*!***************************************!*\
  !*** ./src/api/routes/credentials.ts ***!
  \***************************************/(e,t,r)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0});const n=r(/*! itty-router */"./node_modules/itty-router/dist/itty-router.min.js").Router({base:"/api/credentials"});n.all("/",()=>new Response(JSON.stringify({ping:"pong"}))),t.default=n},"./src/error_handler.ts":
/*!******************************!*\
  !*** ./src/error_handler.ts ***!
  \******************************/(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=e=>new Response(e.message||"Internal Server Error",{status:e.status||500})},"./src/handler.ts":
/*!************************!*\
  !*** ./src/handler.ts ***!
  \************************/function(e,t,r){"use strict";var n=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0});const o=n(r(/*! ./router */"./src/router.ts"));t.default=async e=>await o.default.handle(e)},"./src/index.ts":
/*!**********************!*\
  !*** ./src/index.ts ***!
  \**********************/function(e,t,r){"use strict";var n=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0});const o=n(r(/*! ./handler */"./src/handler.ts"));self.addEventListener("fetch",e=>{const t=e;t.respondWith(o.default(t.request))})},"./src/router.ts":
/*!***********************!*\
  !*** ./src/router.ts ***!
  \***********************/function(e,t,r){"use strict";var n=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0});const o=r(/*! itty-router */"./node_modules/itty-router/dist/itty-router.min.js"),s=n(r(/*! ./api/routes/authentication */"./src/api/routes/authentication.ts")),u=n(r(/*! ./api/routes/credentials */"./src/api/routes/credentials.ts")),a=n(r(/*! ./error_handler */"./src/error_handler.ts")),i=o.Router({base:"/api"});i.all("/authentication/*",s.default.handle).all("/credentials/*",u.default.handle).all("*",a.default),t.default=i}},n={},function e(t){var o=n[t];if(void 0!==o)return o.exports;var s=n[t]={exports:{}};return r[t].call(s.exports,s,s.exports,e),s.exports}("./src/index.ts")}]);